import {
    Bookmark,
    Briefcase,
    Calendar,
    Flame,
    Folder,
    Globe,
    Heart,
    Home,
    MessageCircle,
    Rocket,
    Settings,
    Shield,
    Star,
    User,
    Zap,
} from 'lucide-react';

export const WORKSPACE_ICON_MAP = {
    home: Home,
    briefcase: Briefcase,
    star: Star,
    flame: Flame,
    heart: Heart,
    user: User,
    folder: Folder,
    zap: Zap,
    settings: Settings,
    globe: Globe,
    calendar: Calendar,
    chat: MessageCircle,
    shield: Shield,
    rocket: Rocket,
    bookmark: Bookmark,
} as const;
